// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrFTwv-BtjdAvSeS6-M8nVmS4vzroUNdg',
    appId: '1:809673304602:web:ce7b15f04aac07a044bfa3',
    messagingSenderId: '809673304602',
    projectId: 'swipemeet-ec91e',
    authDomain: 'swipemeet-ec91e.firebaseapp.com',
    storageBucket: 'swipemeet-ec91e.firebasestorage.app',
    measurementId: 'G-70SXVELR31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt_n0Jr0n3zvM7JjjPWDxkhhvj0MezU5c',
    appId: '1:809673304602:android:cfed46287766987844bfa3',
    messagingSenderId: '809673304602',
    projectId: 'swipemeet-ec91e',
    storageBucket: 'swipemeet-ec91e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Pl87oYkHnr5c2VmPaM_P7BftkIigtKs',
    appId: '1:809673304602:ios:d095d011b6fb999944bfa3',
    messagingSenderId: '809673304602',
    projectId: 'swipemeet-ec91e',
    storageBucket: 'swipemeet-ec91e.firebasestorage.app',
    iosBundleId: 'com.example.swipemeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Pl87oYkHnr5c2VmPaM_P7BftkIigtKs',
    appId: '1:809673304602:ios:d095d011b6fb999944bfa3',
    messagingSenderId: '809673304602',
    projectId: 'swipemeet-ec91e',
    storageBucket: 'swipemeet-ec91e.firebasestorage.app',
    iosBundleId: 'com.example.swipemeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrFTwv-BtjdAvSeS6-M8nVmS4vzroUNdg',
    appId: '1:809673304602:web:a2437b45f4d4c70844bfa3',
    messagingSenderId: '809673304602',
    projectId: 'swipemeet-ec91e',
    authDomain: 'swipemeet-ec91e.firebaseapp.com',
    storageBucket: 'swipemeet-ec91e.firebasestorage.app',
    measurementId: 'G-JPSW6WJX2E',
  );
}
